import type { Metadata } from 'next';
import { Fira_Code } from 'next/font/google';
import '../styles/variables.css';
import '../styles/globals.css';
import React from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const firaCode = Fira_Code({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={firaCode.className}>{children}</body>
    </html>
  );
}
