import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import '../styles/variables.css';
import '../styles/globals.css';
import React from 'react';
import { PageTransition } from '@/components/page-transition/PageTransition';
import { StairTransition } from '@/components/stair-transition/StairTransition';
import { Header } from '@/components/header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const firaCode = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: '--font-jetbrainsMono',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={firaCode.variable}>
        <Header />
        <StairTransition />
        <PageTransition> {children}</PageTransition>
      </body>
    </html>
  );
}
